### ISSUE TITLE
`kubeflow-dashboard-operator` fails to build during integration tests

### ISSUE THREAD

**Issue by DnPlas** [canonical/kubeflow-dashboard-operator#147]
Seems like this charm cannot be built during integration tests, resulting in the following error message:

```
RuntimeError: Failed to build charm .:
Packing the charm.
Launching environment to pack for base name='ubuntu' channel='20.04' architectures=['amd64'] (may take a while the first time but it's reusable)
Packing the charm
Packing the charm.
Building charm in '/root'
Running step PULL for part 'charm'
Running step BUILD for part 'charm'
Parts processing error: Failed to run the build script for part 'charm'.
Failed to build charm for bases index '0'.
Full execution log: '/home/runner/.local/state/charmcraft/log/charmcraft-20230724-102034.513526.log'
```

Logs and details in the latest [integration tests job](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5643586071/job/15285722021) for #140

**Comment by DnPlas** [comment]
The [publish job](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/5643586071/job/15285727700#step:5:14) may be affected by this issue.

**Comment by DnPlas** [comment]
From the logs of a failed build, it seems like the problem is with python dependencies that cannot be built correctly because `maturin` (a dependency of `rdps-py`, which is a dependency of `jsonschema`, which is a dependency of `serialized-data-interface`) requires the rust toolchain to be built from source.

<details>
  <summary>charmcraft pack logs</summary>
```
::    :: Collecting rpds-py==0.9.2 (from -r requirements.txt (line 75))                                                                                                                                                                 
::    ::   Using cached rpds_py-0.9.2.tar.gz (16 kB)                                                                                                                                                                                    
::    ::   Installing build dependencies: started                                                                                                                                                                                       
::    ::   Installing build dependencies: finished with status 'error'                                                                                                                                                                  
::    ::   error: subprocess-exited-with-error                                                                                                                                                                                          
::    ::                                                                                                                                                                                                                                
::    ::   × pip subprocess to install build dependencies did not run successfully.                                                                                                                                                     
::    ::   │ exit code: 1                                                                                                                                                                                                               
::    ::   ╰─> [48 lines of output]                                                                                                                                                                                                     
::    ::       Collecting maturin<2.0,>=1.0                                                                                                                                                                                             
::    ::         Using cached maturin-1.1.0.tar.gz (181 kB)                                                                                                                                                                             
::    ::         Installing build dependencies: started                                                                                                                                                                                 
::    ::         Installing build dependencies: finished with status 'done'                                                                                                                                                             
::    ::         Getting requirements to build wheel: started                                                                                                                                                                           
::    ::         Getting requirements to build wheel: finished with status 'done'                                                                                                                                                       
::    ::         Preparing metadata (pyproject.toml): started                                                                                                                                                                           
::    ::         Preparing metadata (pyproject.toml): finished with status 'done'                                                                                                                                                       
::    ::       Collecting tomli>=1.1.0 (from maturin<2.0,>=1.0)                                                                                                                                                                         
::    ::         Using cached tomli-2.0.1-py3-none-any.whl                                                                                                                                                                              
::    ::       Building wheels for collected packages: maturin                                                                                                                                                                          
::    ::         Building wheel for maturin (pyproject.toml): started                                                                                                                                                                   
::    ::         Building wheel for maturin (pyproject.toml): finished with status 'error'                                                                                                                                              
::    ::         error: subprocess-exited-with-error                                                                                                                                                                                    
::    ::                                                                                                                                                                                                                                
::    ::         × Building wheel for maturin (pyproject.toml) did not run successfully.                                                                                                                                                
::    ::         │ exit code: 1                                                                                                                                                                                                         
::    ::         ╰─> [24 lines of output]                                                                                                                                                                                               
::    ::             running bdist_wheel                                                                                                                                                                                                
::    ::             running build                                                                                                                                                                                                      
::    ::             running build_py                                                                                                                                                                                                   
::    ::             creating build                                                                                                                                                                                                     
::    ::             creating build/lib.linux-x86_64-cpython-38                                                                                                                                                                         
::    ::             creating build/lib.linux-x86_64-cpython-38/maturin                                                                                                                                                                 
::    ::             copying maturin/__main__.py -> build/lib.linux-x86_64-cpython-38/maturin                                                                                                                                           
::    ::             copying maturin/__init__.py -> build/lib.linux-x86_64-cpython-38/maturin                                                                                                                                           
::    ::             copying maturin/import_hook.py -> build/lib.linux-x86_64-cpython-38/maturin                                                                                                                                        
::    ::             running egg_info                                                                                                                                                                                                   
::    ::             creating maturin.egg-info                                                                                                                                                                                          
::    ::             writing maturin.egg-info/PKG-INFO                                                                                                                                                                                  
::    ::             writing dependency_links to maturin.egg-info/dependency_links.txt                                                                                                                                                  
::    ::             writing requirements to maturin.egg-info/requires.txt                                                                                                                                                              
::    ::             writing top-level names to maturin.egg-info/top_level.txt                                                                                                                                                          
::    ::             writing manifest file 'maturin.egg-info/SOURCES.txt'                                                                                                                                                               
::    ::             reading manifest file 'maturin.egg-info/SOURCES.txt'                                                                                                                                                               
::    ::             reading manifest template 'MANIFEST.in'                                                                                                                                                                            
::    ::             warning: no files found matching '*.json' under directory 'src/python_interpreter'                                                                                                                                 
::    ::             writing manifest file 'maturin.egg-info/SOURCES.txt'                                                                                                                                                               
::    ::             running build_ext                                                                                                                                                                                                  
::    ::             running build_rust                                                                                                                                                                                                 
::    ::             cargo build --manifest-path Cargo.toml --message-format=json-render-diagnostics --release -v --no-default-features --locked                                                                                        
::    ::             error: Unable to execute 'cargo' - this package requires Rust to be installed and cargo to be on the PATH                                                                                                          
::    ::             [end of output]                                                                                                                                                                                                    
::    ::                                                                                                                                                                                                                                
::    ::         note: This error originates from a subprocess, and is likely not a problem with pip.                                                                                                                                   
::    ::         ERROR: Failed building wheel for maturin                                                                                                                                                                               
::    ::       Failed to build maturin                                                                                                                                                                                                  
::    ::       ERROR: Could not build wheels for maturin, which is required to install pyproject.toml-based projects                                                                                                                    
::    ::       [end of output]                                                                                                                                                                                                          
::    ::                                                                                                                                                                                                                                
::    ::   note: This error originates from a subprocess, and is likely not a problem with pip.                                                                                                                                         
::    :: error: subprocess-exited-with-error                                                                                                                                                                                            
::    ::                                                                                                                                                                                                                                
::    :: × pip subprocess to install build dependencies did not run successfully.                                                                                                                                                       
::    :: │ exit code: 1                                                                                                                                                                                                                 
::    :: ╰─> See above for output.                                                                                                                                                                                                      
::    ::                                                                                                                                                                                                                                
::    :: note: This error originates from a subprocess, and is likely not a problem with pip.                                                                                                                                           
:: Traceback (most recent call last):                                                                                                                                                                                                   
::   File "/snap/charmcraft/1349/lib/charmcraft/charm_builder.py", line 435, in <module>                                                                                                                                                
::     main()                                                                                                                                                                                                                           
::   File "/snap/charmcraft/1349/lib/charmcraft/charm_builder.py", line 430, in main                                                                                                                                                    
::     builder.build_charm()                                                                                                                                                                                                            
::   File "/snap/charmcraft/1349/lib/charmcraft/charm_builder.py", line 103, in build_charm                                                                                                                                             
::     self.handle_dependencies()                                                                                                                                                                                                       
::   File "/snap/charmcraft/1349/lib/charmcraft/charm_builder.py", line 317, in handle_dependencies                                                                                                                                     
::     self._install_dependencies(staging_venv_dir)                                                                                                                                                                                     
::   File "/snap/charmcraft/1349/lib/charmcraft/instrum.py", line 152, in _f                                                                                                                                                            
::     return func(*args, **kwargs)                                                                                                                                                                                                     
::   File "/snap/charmcraft/1349/lib/charmcraft/charm_builder.py", line 271, in _install_dependencies                                                                                                                                   
::     _process_run(cmd)                                                                                                                                                                                                                
::   File "/snap/charmcraft/1349/lib/charmcraft/charm_builder.py", line 371, in _process_run                                                                                                                                            
::     raise RuntimeError(f"Subprocess command {cmd} execution failed with retcode {retcode}")                                                                                                                                          
:: RuntimeError: Subprocess command ['/root/parts/charm/build/staging-venv/bin/pip3', 'install', '--upgrade', '--no-binary', ':all:', '--requirement=requirements.txt'] execution failed with retcode 1                                 
Parts processing error: Failed to run the build script for part 'charm'.                                                                                                                                                                
Failed to build charm for bases index '0'.                                                                                                                                                                                              
Full execution log: '/home/ubuntu/.local/state/charmcraft/log/charmcraft-20230724-144949.605632.log'     
```
</details>

#### Proposed solution (workaround)
Install jsonschema from its binary form to avoid pulling dependencies that introduce these kind of issues. This workaround can be removed after we no longer need SDI for this charm.

```diff
--- a/charmcraft.yaml
+++ b/charmcraft.yaml
@@ -15,3 +15,4 @@ parts:
       - files/*yaml
     # do not use these versions due to pypa/setuptools_scm#713
     charm-python-packages: [ setuptools!=62.2.0, pip!=22.1 ]
+    charm-binary-python-packages: [jsonschema]
```
